### ISSUE TITLE
color.fade([delta=0.2])

### ISSUE THREAD

**Issue by mbostock** [d3/d3-color#32]
Similar to *color*.brighter, but for succinctly modifying the opacity channel. It could return a new color whose opacity is max(0, min(1, this.opacity - *delta*)).

**Comment by curran** [comment]
Very cool idea! I've come across a need for such a thing when desiring the fill and stroke colors both to be data-driven, but having the fill more opaque than the stroke for a nice "popping" effect.

FWIW, I have been using the following CSS technique to accomplish this:

```css
.mark {
  fill: currentColor;
  stroke: currentColor;
  fill-opacity: 0.3;
}
```

I learned only recently about the `currentColor` CSS keyword (HT @seemantk), which will use the value of the `color` attribute, so you can compute the colors only once with `selection.attr("color", ...)`.
